User.destroy_all
Recipe.destroy_all
Rating.destroy_all
Comment.destroy_all

# Users
hannah = User.create(name: "Hannah Kofkin", username: "hkofkin", password: "1234", email: "hkofkin@gmail.com")
jack = User.create(name: "Jack Hilscher", username: "jackattack", password: "1234", email: "jack@hilscher.com")
rei = User.create(name: "Rei Reynoso", username: "reiofsunshine", password: "1234", email: "rei@rey.com")
michelle = User.create(name: "Michelle Rios", username: "michlovesmemes", password: "1234", email: "mich@memes.com")
ian = User.create(name: "Ian Hollander", username: "kingian", password: "1234", email: "ian@isking.com")

# Recipes
test_recipe_1 = Recipe.create(user_id: hannah.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1596921748/Food%20Feed/FB_fried_mac_thumbThumb_qzkusy.jpg", video: "https://res.cloudinary.com/hsk23/video/upload/v1596921779/Food%20Feed/1489681283_vxw2gm.mp4", title: "Fried Mac 'n' Cheese Sticks", favorited: true)
test_recipe_2 = Recipe.create(user_id: jack.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597081112/Food%20Feed/62298_f0chst.jpg", video: "https://res.cloudinary.com/hsk23/video/upload/v1597081161/Food%20Feed/1497287402_f5ttol.mp4", title: "The Best Chewy Chocolate Chip Cookies", favorited: false)
test_recipe_3 = Recipe.create(user_id: rei.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922353/262316_cjswo5.jpg", video: "", title: "Zesty One-Pot Shrimp Pasta", favorited: false)
test_recipe_4 = Recipe.create(user_id: michelle.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922352/39637_cnue5z.jpg", video: "", title: "Tomato, Basil & Mozzarella Chicken", favorited: false)
test_recipe_5 = Recipe.create(user_id: ian.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922352/BFV12484_3-IngredientDinners-FB1080SQ_uuwsue.jpg", video: "", title: "3-ingredient Cajun BBQ Ribs", favorited: false)
test_recipe_6 = Recipe.create(user_id: hannah.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922352/5d9a390b4a7d43a8a5d7f46db5b0e4e8_wsxgnk.jpg", video: "", title: "1-2-3 Cheesecake", favorited: false)
test_recipe_7 = Recipe.create(user_id: jack.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922353/SugarGlazedAppleTart_FB_Thumbnail_qm6ii0.jpg", video: "", title: "Sugar Glazed Apple Tart", favorited: false)
test_recipe_8 = Recipe.create(user_id: rei.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922353/BFV27473_5-IngredientCauliflowerMacNCheese-ThumbTextless_ujoh83.jpg", video: "", title: "Cauliflower Mac ‘N’ Cheese", favorited: false)
test_recipe_9 = Recipe.create(user_id: michelle.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922353/THUMBNAIL_C_badjjt.jpg", video: "", title: "Pork Chops And Creamy Spinach", favorited: false)
test_recipe_10 = Recipe.create(user_id: ian.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922352/BFV12484_3-IngredientDinners-FB1080SQ-1_mkuf51.jpg", video: "", title: "Chili-glazed Salmon", favorited: false)
test_recipe_11 = Recipe.create(user_id: hannah.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922353/BFV21474_2-Ingredient_Sorbet_4_Ways_FB_V1_jlhynr.jpg", video: "", title: "Strawberry 2-Ingredient Sorbet", favorited: false)
test_recipe_12 = Recipe.create(user_id: jack.id, image: "https://res.cloudinary.com/hsk23/image/upload/v1597922352/a3506c00c48749539c485b81c229991d_tosdwq.jpg", video: "", title: "Sungyi's S’mores Cookies", favorited: false)

# Ingredients
ing1 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "8 oz elbow pasta")
ing2 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "4 tablespoons butter")
ing3 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "2 ¼ cups flour, divided")
ing4 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "2 cups milk")
ing5 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "1 teaspoon salt")
ing6 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "½ teaspoon black pepper")
ing7 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "2 cups shredded sharp cheddar cheese")
ing8 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "peanut or vegetable oil, for frying")
ing9 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "4 eggs, beaten")
ing10 = Ingredient.create(recipe_id: test_recipe_1.id, ingred_detail: "2 cups bread crumbs")

ing11 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "½ cup granulated sugar")
ing12 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "¾ cup brown sugar packed")
ing13 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "1 teaspoon salt")
ing14 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "½ cup unsalted butter melted")
ing15 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "1 egg")
ing16 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "1 teaspoon vanilla extract")
ing17 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "1 ¼ cups all-purpose flour")
ing18 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "½ teaspoon baking soda")
ing19 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "4 oz milk or semi-sweet chocolate chunks")
ing20 = Ingredient.create(recipe_id: test_recipe_2.id, ingred_detail: "4 oz dark chocolate chunk or your preference")

ing20 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "kosher salt, for cooking pasta")
ing21 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "8 oz linguine")
ing22 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "8 tablespoons unsalted butter, divided")
ing23 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "1 ¼ lb large shrimp")
ing24 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "1 pouch Tasty Zesty Spice Blend")
ing25 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "4 cups fresh baby spinach")
ing26 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "¼ cup grated parmesan cheese")
ing27 = Ingredient.create(recipe_id: test_recipe_3.id, ingred_detail: "2 tablespoons fresh lemon juice")

ing27 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "2 boneless, skinless chicken breasts")
ing28 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "olive oil, to taste")
ing29 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "salt, to taste")
ing30 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "pepper, to taste")
ing31 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "garlic powder, to taste")
ing32 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "oregano, to taste")
ing33 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "1 ball fresh mozzarella cheese")
ing34 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "1 tomato, medium")
ing35 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "5 leaves fresh basil leaf")
ing36 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "1 cup dark balsamic vinegar, inexpensive")
ing37 = Ingredient.create(recipe_id: test_recipe_4.id, ingred_detail: "⅓ cup honey")

ing38 = Ingredient.create(recipe_id: test_recipe_5.id, ingred_detail: "½ rack baby back ribs")
ing39 = Ingredient.create(recipe_id: test_recipe_5.id, ingred_detail: "3 tablespoons cajun seasoning")
ing40 = Ingredient.create(recipe_id: test_recipe_5.id, ingred_detail: "1 cup BBQ sauce")

ing41 = Ingredient.create(recipe_id: test_recipe_6.id, ingred_detail: "1 can sweetened condensed milk, 14 ounce can (395 G)")
ing42 = Ingredient.create(recipe_id: test_recipe_6.id, ingred_detail: "2 blocks cream cheese, 8 ounce blockes (450 G)")
ing43 = Ingredient.create(recipe_id: test_recipe_6.id, ingred_detail: "3 large eggs")
ing44 = Ingredient.create(recipe_id: test_recipe_6.id, ingred_detail: "1 pie pan, (if not using a crust, butter the pan)")

ing45 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "⅔ cup all-purpose flour")
ing46 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "3 tablespoons unsalted butter, cut into 3 equal pieces")
ing47 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "1 tablespoon canola oil")
ing48 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "½ teaspoon sugar")
ing49 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "⅛ teaspoon salt")
ing50 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "1 tablespoon water, ice-cold")
ing51 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "2 apples, cut into slices")
ing52 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "2 tablespoons sugar, topping")
ing53 = Ingredient.create(recipe_id: test_recipe_7.id, ingred_detail: "3 tablespoons butter, topping, cut into small cubes")

ing53 = Ingredient.create(recipe_id: test_recipe_8.id, ingred_detail: "1 head cauliflower")
ing54 = Ingredient.create(recipe_id: test_recipe_8.id, ingred_detail: "salt, to taste")
ing55 = Ingredient.create(recipe_id: test_recipe_8.id, ingred_detail: "pepper, to taste")
ing56 = Ingredient.create(recipe_id: test_recipe_8.id, ingred_detail: "¼ cup sour cream, or greek yogurt")
ing57 = Ingredient.create(recipe_id: test_recipe_8.id, ingred_detail: "½ cup shredded cheddar cheese")
ing58 = Ingredient.create(recipe_id: test_recipe_8.id, ingred_detail: "fresh parsley, chopped, optional")

ing59 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "olive oil, to taste")
ing60 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "¼ cup onion, minced")
ing61 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "2 cloves garlic, minced")
ing62 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "7 oz spinach, washed")
ing63 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "6 oz cream cheese, cubed")
ing64 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "salt, to taste")
ing65 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "pepper, to taste")
ing66 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "5 thick-cut pork chops")
ing67 = Ingredient.create(recipe_id: test_recipe_9.id, ingred_detail: "mashed potato, for serving")

ing68 = Ingredient.create(recipe_id: test_recipe_10.id, ingred_detail: "4 oz salmon, 3 fillets")
ing69 = Ingredient.create(recipe_id: test_recipe_10.id, ingred_detail: "½ cup chili sauce")
ing70 = Ingredient.create(recipe_id: test_recipe_10.id, ingred_detail: "¼ cup fresh scallions, chopped")

ing71 = Ingredient.create(recipe_id: test_recipe_11.id, ingred_detail: "1 lb strawberry")
ing72 = Ingredient.create(recipe_id: test_recipe_11.id, ingred_detail: "¼ cup honey")

ing73 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "½ cup butter")
ing74 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "¼ cup graham cracker, crushed")
ing75 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "¼ cup brown sugar")
ing76 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "3 tablespoons granulated sugar")
ing77 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "1 teaspoon vanilla extract")
ing78 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "1 egg")
ing79 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "1 cup flour")
ing80 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "¼ teaspoon salt")
ing81 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "¼ cup chocolate chips")
ing82 = Ingredient.create(recipe_id: test_recipe_12.id, ingred_detail: "¼ cup marshmallow")


# Recipe Steps
step1 = RecipeStep.create(recipe_id: test_recipe_1.id, step_detail: "Bring 3 quarts of water to a boil in a medium pot and cook the elbow pasta. Stir occasionally for 7 minutes, or until al dente.")
step2 = RecipeStep.create(recipe_id: test_recipe_1.id, step_detail: "In a large saucepan over medium-low heat, melt the butter completely and whisk in ¼ cup flour for 2 minutes to create a light roux. Add the milk and season the mixture with salt and pepper. Stir continuously until the sauce fully thickens. Gradually add the cheese and stir until fully combined. Finally, add the cooked pasta and stir until the noodles are well-coated.")
step3 = RecipeStep.create(recipe_id: test_recipe_1.id, step_detail: "Remove the mac ’n’ cheese from the heat and pour onto a parchment-lined baking sheet. Spread evenly and freeze for 2 hours.")
step4 = RecipeStep.create(recipe_id: test_recipe_1.id, step_detail: "Heat the oil in a large pot until it reaches 325°F (170°C).")
step5 = RecipeStep.create(recipe_id: test_recipe_1.id, step_detail: "Cut the frozen mac ’n’ cheese into roughly 3-inch long sticks. Dredge the sticks in the remaining 2 cups flour, then the egg, and then the bread crumbs. Fry the sticks for 2-3 minutes or until golden brown, then drain on paper towels and sprinkle with salt. Serve immediately.")

step6 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "In a large bowl, whisk together the sugars, salt, and butter until a paste forms with no lumps.")
step7 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Whisk in the egg and vanilla, beating until light ribbons fall off the whisk and remain for a short while before falling back into the mixture.")
step8 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Sift in the flour and baking soda, then fold the mixture with a spatula (Be careful not to overmix, which would cause the gluten in the flour to toughen resulting in cakier cookies).")
step9 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Fold in the chocolate chunks, then chill the dough for at least 30 minutes. For a more intense toffee-like flavor and deeper color, chill the dough overnight. The longer the dough rests, the more complex its flavor will be.")
step10 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Preheat oven to 350°F (180°C). Line a baking sheet with parchment paper.")
step11 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Scoop the dough with an ice-cream scoop onto a parchment paper-lined baking sheet, leaving at least 4 inches (10 cm) of space between cookies and 2 inches (5 cm) of space from the edges of the pan so that the cookies can spread evenly.")
step12 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Bake for 12-15 minutes, or until the edges have started to barely brown.")
step13 = RecipeStep.create(recipe_id: test_recipe_2.id, step_detail: "Cool completely before serving.")

step14 = RecipeStep.create(recipe_id: test_recipe_3.id, step_detail: "Bring a large pot of salted water to a boil. Add the pasta and cook, stirring frequently, until al dente, about 9 minutes. Drain the pasta and set aside.")
step15 = RecipeStep.create(recipe_id: test_recipe_3.id, step_detail: "In the same pot, heat 2 tablespoons of butter over medium heat. When the butter has melted, add the shrimp and season with the Zesty seasoning. Cook until the shrimp start to turn pink, but are not fully cooked, about 3 minutes. Add the spinach and cook until wilted, about 3 minutes.")
step16 = RecipeStep.create(recipe_id: test_recipe_3.id, step_detail: "Add the linguine to the pot, along with the remaining 6 tablespoons of butter and Parmesan. Toss until the butter melts and the pasta is well-coated. Add the lemon juice and toss once more to incorporate.")
step17 = RecipeStep.create(recipe_id: test_recipe_3.id, step_detail: "Serve the pasta hot.")

step17 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "Preheat oven to 400°F (200°C).")
step18 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "On a parchment-lined baking sheet, season both sides of the chicken with olive oil, salt, pepper, garlic powder, and oregano.")
step19 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "Bake for 30 minutes, or until cooked through and juices run clear.")
step20 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "While the chicken is in the oven, combine the balsamic vinegar and honey in a sauce pot and simmer, stirring occasionally.")
step21 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "NOTE: It should take about 20 minutes for the mixture to reduce.")
step22 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "Once the glaze has reached your desired thickness, remove it from the heat and set aside.")
step23 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "Remove the chicken from the oven and top with slices of mozzarella and tomato.")
step24 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "Broil for 8-10 minutes, or until the cheese is melty and the tomatoes are slightly charred.")
step25 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "While the chicken is broiling, you can chiffonade (cut into thin strips) the basil.")
step26 = RecipeStep.create(recipe_id: test_recipe_4.id, step_detail: "Drizzle the balsamic glaze over the chicken and top with basil.")

step27 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Preheat oven to 250°F (120°C).")
step28 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Rub the Cajun seasoning evenly over the top and bottom of the ribs.")
step29 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Bake for 2 hours, until ribs are tender.")
step30 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Increase oven temperature to 500°F (260°C).")
step31 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Brush the BBQ sauce evenly over the top and the sides.")
step32 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Bake for an additional 15 minutes, until the sauce is bubbly and caramelized.")
step33 = RecipeStep.create(recipe_id: test_recipe_5.id, step_detail: "Serve with the extra BBQ sauce!")

step34 = RecipeStep.create(recipe_id: test_recipe_6.id, step_detail: "Preheat oven to 350°F (180°C).")
step35 = RecipeStep.create(recipe_id: test_recipe_6.id, step_detail: "Mix sweetened condensed milk, cream cheese, and eggs until smooth. Pour into the pan and bake 30–60 minutes, or until a toothpick inserted into the center comes out clean (the cheesecake will still be jiggly).")
step36 = RecipeStep.create(recipe_id: test_recipe_6.id, step_detail: "Take out the cheesecake and let cool. Cut into 8 slices and serve.")

step37 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Preheat the oven to 400°F (200°C).")
step38 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "For the dough, put the flour, butter, oil, sugar, and salt in a food processor and process for about 10 seconds.")
step39 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Add the Tablespoon of ice water and process for another five or six seconds.")
step40 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Remove from the bowl and form into a flat dough. Wrap the dough with plastic wrap and then refrigerate for 20-30 minutes.")
step41 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Lightly flour a work surface and roll the ball of dough into a thin layer, around ¼ inch (6 ⅓ mm) thick.")
step42 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Using a round cutter, or use a round bowl or lid as a guide and cut out into a nice round circle. Carefully transfer the dough to a large cookie sheet lined with a nonstick baking mat.")
step43 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Arrange the apple slices, alternating them nicely on top of the dough. Sprinkle the apple with sugar and put butter cubes on top.")
step44 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Bake for 30 to 35 minutes, until the fruit is soft and the dough nicely browned.")
step45 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Some of the juice from the fruit will have leaked out onto the cookie sheet. Before it hardens and makes the disks stick to the sheet, lift the tart with a broad spatula and transfer them to a cooling rack or platter.")
step46 = RecipeStep.create(recipe_id: test_recipe_7.id, step_detail: "Serve lukewarm or at room temperature with ice cream (optional).")

step47 = RecipeStep.create(recipe_id: test_recipe_8.id, step_detail: "Cut cauliflower into small florets, about 4 cups (1.2 kg).")
step48 = RecipeStep.create(recipe_id: test_recipe_8.id, step_detail: "Add cauliflower florets into a 6-quart (6 L) Dutch oven of boiling water and boil for 5 minutes.")
step49 = RecipeStep.create(recipe_id: test_recipe_8.id, step_detail: "Drain the cauliflower in a colander, and return to the pot. Reduce heat to low.")
step50 = RecipeStep.create(recipe_id: test_recipe_8.id, step_detail: "Add in salt, pepper, and sour cream, and stir until thoroughly combined.")
step51 = RecipeStep.create(recipe_id: test_recipe_8.id, step_detail: "Stir in cheddar cheese until melted.")
step52 = RecipeStep.create(recipe_id: test_recipe_8.id, step_detail: "Remove from heat. Top with parsley (optional).")

step53 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Preheat the oven to 400°F (200°C).")
step54 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Heat the olive oil in a medium pan over medium heat. Add the onion and sauté until translucent, about 2 minutes. Add the garlic and cook until fragrant, about 1 minute.")
step55 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Add the spinach and cool until wilted.")
step56 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Add the cream cheese and stir until melted. Season with salt and pepper. Remove the pan from the heat and let cool.")
step57 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Make a slit on the side of each pork chop to make a pocket, but do not cut all the way through.")
step58 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Fill the pork chops with the spinach mixture. Season with salt and pepper on both sides.")
step59 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Heat a drizzle of olive oil in a large pan over medium-high heat. Working in batches, sear the pork chops until golden brown on both sides. Transfer to a baking sheet.")
step60 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Bake the pork chops for 20 minutes, or until cooked through.")
step61 = RecipeStep.create(recipe_id: test_recipe_9.id, step_detail: "Serve the pork chops with mashed potatoes.")

step62 = RecipeStep.create(recipe_id: test_recipe_10.id, step_detail: "Preheat oven to 400°F (200˚C).")
step63 = RecipeStep.create(recipe_id: test_recipe_10.id, step_detail: "In a bowl, mix together the salmon, chili sauce, and the scallions.")
step64 = RecipeStep.create(recipe_id: test_recipe_10.id, step_detail: "Place the fillets on a baking tray lined with parchment paper. Spoon any leftover sauce on top of the salmon.")
step65 = RecipeStep.create(recipe_id: test_recipe_10.id, step_detail: "Bake for 12-15 minutes, until the salmon is cooked but still tender.")

step66 = RecipeStep.create(recipe_id: test_recipe_11.id, step_detail: "Hull the strawberries by using a straw to push out the stem of each strawberry.")
step67 = RecipeStep.create(recipe_id: test_recipe_11.id, step_detail: "Cut strawberries in half and place on a parchment paper-lined baking sheet and freeze until hardened.")
step68 = RecipeStep.create(recipe_id: test_recipe_11.id, step_detail: "Add the frozen strawberries and honey to a food processor and combine until evenly mixed.")
step69 = RecipeStep.create(recipe_id: test_recipe_11.id, step_detail: "Transfer to a loaf pan and transfer to freezer until completely frozen.")

step70 = RecipeStep.create(recipe_id: test_recipe_12.id, step_detail: "Brown the butter in a pan.")
step71 = RecipeStep.create(recipe_id: test_recipe_12.id, step_detail: "Soak the graham cracker crumbs in the butter to soften the crumbs. You can also add the sugars now.")
step72 = RecipeStep.create(recipe_id: test_recipe_12.id, step_detail: "Add everything else except for the marshmallows after the mixture cools.")
step73 = RecipeStep.create(recipe_id: test_recipe_12.id, step_detail: "You can chill the batter for a bit! If not, preheat the oven to 350°F (180°C) and form the cookies onto a parchment paper-lined cookie sheet")
step74 = RecipeStep.create(recipe_id: test_recipe_12.id, step_detail: "Add the marshmallows to the center of the cookie shapes. They will melt and puff up and caramelize, so make sure they're in the center and not the edge so they don't melt and burn at the edges of the cookie!!")
step75 = RecipeStep.create(recipe_id: test_recipe_12.id, step_detail: "Bake for 12-15 minutes. Let cool and enjoy!")


# Ratings
rating1 = Rating.create(user_id: jack.id, recipe_id: test_recipe_1.id, value: 4)
rating2 = Rating.create(user_id: hannah.id, recipe_id: test_recipe_1.id, value: 5)

# Comments
comment1 = Comment.create(user_id: jack.id, recipe_id: test_recipe_1.id, content: "this was delicious and recipe was easy to follow")
comment1 = Comment.create(user_id: hannah.id, recipe_id: test_recipe_1.id, content: "can't wait for more people to try this!")

puts 'Seeded.'